language: node_js
branches:
  only:
    - master
    - /^greenkeeper.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # Allow vX.X.X tags
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      name: Lint code
      node_js: lts/*
      script:
        - npm run dev
        - npm run lint
        - yarn --cwd ./demo run lint
    - stage: test
      name: Run tests (Node.js Current)
      node_js: node
      script:
        - npm run dev
        - npm test
    - stage: test
      name: Run tests (Node.js LTS)
      node_js: lts/*
      script:
        - npm install -g codecov
        - npm run dev
        - npm test
        - codecov
    - stage: deploy
      if: type = push AND tag IS present
      name: Deploy to npm
      node_js: lts/*
      script:
        - npm run dev
        - npm run compile
        - echo "Deploying to npm..."
      deploy:
        skip_cleanup: true
        provider: npm
        email: wes@sparksuite.com
        api_key:
          secure: OTUxkiEVzOsC8OM2tc+dITVMQp2fxa+X3VRfLwUBoH/EQmd0h9m6MVQVviMSGHSZZ7NZqEEjx1wh3OIJ+9k2ov7Snn0LZc9Q+zU6QpvMuK1VemCCeJl0NYl5BaWNqFAlTmC3fPC6Z7btVMDeWdp3YaQ1Kr1EWgth1jgxSepxW9hCacAfwIgTJw/4JhwJKUdA3cETQ6QZTn244dMhTNz/CrLB5DFI/qm83ImIr8iQWtz1qAeMy4peXSLz7IcLkhOIoFVlNcy61jf35HVSOy6T7s6a9RZnUV2VwtWlFxAO/tA9Rzkxw0Oo9LB9worw2TkOY39L9KifUpGl6AESwAKVyXQrqjkt0VrZqq/WKOnwhKfZ83ahZL3TpcUADBM0DpLAX1qFyPYgoZlMaXKX2DaQDmP7X+lSRYokSdVrgvivo/ck50Gnqk4eCW7mpgJ0BspvQznlRzNUdaeSQMSki/7EAWZH29B3VD8WWTwI+8gpEymPignXMpy+kGDxMZiE0+VbRm7m22aCb32Xzui0kIvDcuqjJzE376D4eEodnvkVOTy9RLzcTsVfAkQpBHds+Xaby0U5IEW/CkPHJn1Nuovl153bAp7bAj6JnarCIuTGmrQNq+UNCOQvt88DfjtoQQnJ0UPgDFb/C5uNUEZOU97/W0csNaBmNgE+KdjMVzq0TWs=
        on:
          tags: true
          repo: sparksuite/react-accessible-dropdown-menu-hook
          branch: master
    - stage: deploy
      if: type = push AND tag IS present
      name: Deploy to GitHub Pages
      node_js: lts/*
      script:
        - npm run dev
        - yarn --cwd ./demo install --frozen-lockfile
        - echo "Deploying to GitHub pages..."
      deploy:
        provider: pages
        local_dir: demo/build
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
